import { useEffect, useState } from "react";
import { Activity, ArrowLeft, Check, ChevronDown, ChevronLeft, ChevronRight, Edit3, MessageCircle, Minus, Plus, Save, Send, Trash2 } from "lucide-react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { api } from "../api/client";
import { useAuth } from "../App";
import { Badges, Flag, MiniChart } from "../components/SportsUI";
import { Countdown } from "../components/MatchCard";

const StatCards=({s})=><div className="stat-cards">
  {[["Posición",`#${s.position}`],["Puntos",s.total_points],["Pronósticos",s.predicted_matches],["Ganadores",s.winner_hits],["Exactos",s.exact_hits],["Media",`${s.average_points} pts`]].map(([k,v])=><article key={k}><span>{k}</span><strong>{v}</strong></article>)}
</div>;

export function ProfilePage(){
  const {setUser}=useAuth(); const [data,setData]=useState(null),[phrase,setPhrase]=useState(""),[saved,setSaved]=useState(false);
  const load=()=>api("/profile/me").then(d=>{setData(d);setPhrase(d.user.personal_phrase||"")});
  useEffect(()=>{load()},[]);
  if(!data)return <div className="page-loader"><span/></div>;
  const save=async()=>{const user=await api("/profile/me",{method:"PATCH",body:{personal_phrase:phrase}});setUser(u=>({...u,...user}));setSaved(true);load()};
  const s=data.stats;
  return <div className="page"><section className="profile-hero"><div className="profile-avatar">{data.user.username[0].toUpperCase()}</div><div><span className="eyebrow">PERFIL DE JUGADOR</span><h1>{data.user.username}</h1><p>{data.user.role==="admin"?"Administrador":"Participante"} · Desde {new Date(data.user.created_at).toLocaleDateString("es-ES")}</p></div></section>
    <StatCards s={s}/><section className="content-card"><h2>Mi frase</h2><div className="phrase-editor"><input maxLength="120" value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder="Este año gano yo."/><button className="primary" onClick={save}><Edit3 size={16}/>Guardar</button></div>{saved&&<small className="success-text">Frase actualizada.</small>}</section>
    <StatsSections stats={s} history={data.history}/><section className="content-card"><h2>Medallas</h2><Badges badges={s.badges}/></section>
  </div>
}
function StatsSections({stats:s,history=[]}){return <><div className="insight-grid">{[["Ganadores acertados",`${s.winner_percentage}%`],["Resultados exactos",`${s.exact_percentage}%`],["Mejor jornada",s.best_day?`${s.best_day.points} pts`:"—"],["Peor jornada",s.worst_day?`${s.worst_day.points} pts`:"—"],["Equipo más elegido",s.most_picked_team],["Equipo más rentable",s.best_team]].map(([k,v])=><article className="content-card" key={k}><span>{k}</span><strong>{v}</strong></article>)}</div><div className="chart-grid"><section className="content-card"><h2>Puntos por día</h2><MiniChart data={s.daily}/></section><section className="content-card"><h2>Evolución de posición</h2><MiniChart data={history} field="position" inverse/></section></div></>}
export function PublicProfilePage(){
  const {id}=useParams(),navigate=useNavigate(),[data,setData]=useState(null);useEffect(()=>{api(`/users/${id}/public`).then(setData)},[id]);
  if(!data)return <div className="page-loader"><span/></div>;const s=data.stats;
  return <div className="page"><button className="back-btn" onClick={()=>navigate(-1)}><ArrowLeft size={16}/>Volver</button><section className="profile-hero public"><div className="profile-avatar">{data.user.username[0].toUpperCase()}</div><div><span className="eyebrow">FICHA DEPORTIVA</span><h1>{data.user.username}</h1><blockquote>“{data.user.personal_phrase||"Todavía sin frase personal."}”</blockquote></div><b>#{s.position}</b></section><StatCards s={s}/><StatsSections stats={s} history={data.history}/><section className="content-card"><h2>Medallas</h2><Badges badges={s.badges}/></section><section className="content-card"><h2>Historial visible</h2><div className="prediction-history">{data.predictions.map(p=><div key={p.id}><span>{p.match_date}</span><strong><Flag team={p.team1}/>{p.team1} {p.predicted_team1_goals}–{p.predicted_team2_goals} {p.team2}<Flag team={p.team2}/></strong><b>+{p.total_points}</b></div>)}</div></section></div>
}
export function ActivityPage(){
 const [data,setData]=useState({items:[],page:1,total_pages:1});const load=page=>api(`/activity?page=${page}&page_size=10`).then(response=>setData(Array.isArray(response)?{items:response,page:1,total_pages:1}:response));useEffect(()=>{load(1)},[]);
 return <div className="page narrow"><section className="page-heading"><span className="eyebrow"><Activity size={14}/> COMUNIDAD</span><h1>Actividad reciente</h1><p>Lo último que está pasando en la porra.</p></section><div className="activity-feed">{data.items.map((item,i)=><article key={`${item.type}-${i}-${item.created_at}`}><span className={`feed-icon ${item.type}`}>{item.type==="points"?"+":"⚽"}</span><div><strong>{item.text}</strong><small>{new Date(item.created_at).toLocaleString("es-ES")}</small></div></article>)}</div>{data.total_pages>1&&<nav className="pagination" aria-label="Paginación de actividad"><button disabled={data.page===1} onClick={()=>load(data.page-1)}><ChevronLeft/>Anterior</button><span>Página {data.page} de {data.total_pages}</span><button disabled={data.page===data.total_pages} onClick={()=>load(data.page+1)}>Siguiente<ChevronRight/></button></nav>}</div>
}
function HiddenDistribution({revealAt,onReveal}){
 const [current,setCurrent]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setCurrent(Date.now()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(current>=new Date(revealAt).getTime())onReveal()},[current,revealAt,onReveal]);
 const minutes=Math.max(1,Math.ceil((new Date(revealAt).getTime()-current)/60000));
 return <div className="distribution-hidden"><div className="pixelated-bars" aria-hidden="true"><i/><i/><i/></div><strong>Se podrá ver en {minutes} {minutes===1?"minuto":"minutos"}</strong><span>La distribución está oculta para no influir en los pronósticos.</span></div>
}
export function MatchDetailPage(){
 const {id}=useParams(),navigate=useNavigate(),location=useLocation(),{user}=useAuth(),[data,setData]=useState(null),[comments,setComments]=useState([]),[text,setText]=useState(""),[error,setError]=useState(""),[participantsOpen,setParticipantsOpen]=useState(false),[result,setResult]=useState({g1:"",g2:""}),[savingResult,setSavingResult]=useState(false),[resultMessage,setResultMessage]=useState(""),[pick,setPick]=useState({winner:"",g1:"",g2:""}),[savingPick,setSavingPick]=useState(false),[pickMessage,setPickMessage]=useState("");
 const load=()=>{setError("");return Promise.all([api(`/matches/${id}/detail`),api(`/matches/${id}/comments`)]).then(([d,c])=>{setData(d);setComments(c)}).catch(err=>setError(err.message))};
 useEffect(()=>{load()},[id]);
 useEffect(()=>{if(data)setResult({g1:data.match.result_team1??"",g2:data.match.result_team2??""})},[data?.match.result_team1,data?.match.result_team2]);
 useEffect(()=>{if(data)setPick({winner:data.match.predicted_winner||"",g1:data.match.predicted_team1_goals??"",g2:data.match.predicted_team2_goals??""})},[data?.match.prediction_id,data?.match.predicted_winner,data?.match.predicted_team1_goals,data?.match.predicted_team2_goals]);
 useEffect(()=>{if(data&&location.hash==="#comentarios")requestAnimationFrame(()=>document.getElementById("comentarios")?.scrollIntoView({behavior:"smooth",block:"start"}))},[data,location.hash]);
 if(error)return <div className="page error-page"><section className="content-card"><h1>No se pudo abrir el partido</h1><p>{error}</p><button className="primary" onClick={()=>navigate("/partidos",{replace:true})}><ArrowLeft size={16}/>Volver a partidos</button></section></div>;if(!data)return <div className="page-loader"><span/></div>;const m=data.match,total=data.distribution.reduce((a,x)=>a+x.count,0)||1;
 const add=async()=>{await api(`/matches/${id}/comments`,{method:"POST",body:{comment:text}});setText("");load()};
 const remove=async cid=>{await api(`/comments/${cid}`,{method:"DELETE"});load()};
 const saveResult=async()=>{setSavingResult(true);setResultMessage("");try{await api(`/matches/${id}/finish`,{method:"POST",body:{result_team1:Number(result.g1),result_team2:Number(result.g2)}});setResultMessage("Resultado guardado y puntos recalculados.");await load()}catch(err){setResultMessage(err.message)}finally{setSavingResult(false)}};
 const adjustPick=(field,delta)=>setPick({...pick,[field]:String(Math.max(0,Number(pick[field]||0)+delta))});
 const savePick=async()=>{setSavingPick(true);setPickMessage("");try{await api(m.prediction_id?`/predictions/${m.prediction_id}`:"/predictions",{method:m.prediction_id?"PUT":"POST",body:{match_id:m.id,predicted_winner:pick.winner,predicted_team1_goals:Number(pick.g1),predicted_team2_goals:Number(pick.g2)}});setPickMessage("Pronóstico guardado.");await load()}catch(err){setPickMessage(err.message)}finally{setSavingPick(false)}};
 return <div className="page"><button className="back-btn" onClick={()=>navigate("/partidos",{replace:true})}><ArrowLeft size={16}/>Todos los partidos</button><section className="match-detail-hero"><span>{m.match_date} · {m.match_time} · {m.stadium}</span><div><h1><Flag team={m.team1}/>{m.team1}</h1><b>{m.status==="finished"?`${m.result_team1} – ${m.result_team2}`:"VS"}</b><h1>{m.team2}<Flag team={m.team2}/></h1></div><em>{m.status==="finished"?"Finalizado":m.betting_open?"Pronósticos abiertos":"Pronósticos cerrados"}</em>{m.betting_open&&<div className="detail-countdown"><Countdown date={m.effective_close_at}/></div>}{user.role==="admin"&&<div className="hero-result-editor"><strong>{m.status==="finished"?"Editar resultado del partido":"Introducir resultado del partido"}</strong><div className="result-inputs"><label>{m.team1}<input aria-label={`Resultado de ${m.team1}`} type="number" min="0" inputMode="numeric" value={result.g1} onChange={e=>setResult({...result,g1:e.target.value})}/></label><b>:</b><label>{m.team2}<input aria-label={`Resultado de ${m.team2}`} type="number" min="0" inputMode="numeric" value={result.g2} onChange={e=>setResult({...result,g2:e.target.value})}/></label><button className="primary" disabled={savingResult||result.g1===""||result.g2===""} onClick={saveResult}><Save size={16}/>{savingResult?"Guardando...":"Guardar resultado"}</button></div><small>Al guardar se recalculan automáticamente los puntos.</small>{resultMessage&&<small className={resultMessage.startsWith("Resultado")?"success-text":"error-text"}>{resultMessage}</small>}</div>}</section>
 <div className="detail-grid"><section className="content-card detail-prediction"><h2>Mi pronóstico</h2>{m.betting_open?<><div className="detail-winner-picks"><button className={pick.winner==="team1"?"selected":""} onClick={()=>setPick({...pick,winner:"team1"})}><Flag team={m.team1}/><span>{m.team1}</span>{pick.winner==="team1"&&<Check/>}</button><button className={pick.winner==="draw"?"selected":""} onClick={()=>setPick({...pick,winner:"draw"})}><b>X</b><span>Empate</span>{pick.winner==="draw"&&<Check/>}</button><button className={pick.winner==="team2"?"selected":""} onClick={()=>setPick({...pick,winner:"team2"})}><Flag team={m.team2}/><span>{m.team2}</span>{pick.winner==="team2"&&<Check/>}</button></div><div className="detail-score-picker"><div><small>{m.team1}</small><span><button onClick={()=>adjustPick("g1",-1)}><Minus/></button><input aria-label={`Goles pronosticados de ${m.team1}`} type="number" min="0" inputMode="numeric" value={pick.g1} onChange={e=>setPick({...pick,g1:e.target.value})}/><button onClick={()=>adjustPick("g1",1)}><Plus/></button></span></div><b>:</b><div><small>{m.team2}</small><span><button onClick={()=>adjustPick("g2",-1)}><Minus/></button><input aria-label={`Goles pronosticados de ${m.team2}`} type="number" min="0" inputMode="numeric" value={pick.g2} onChange={e=>setPick({...pick,g2:e.target.value})}/><button onClick={()=>adjustPick("g2",1)}><Plus/></button></span></div></div><button className="primary detail-save-pick" disabled={savingPick||!pick.winner||pick.g1===""||pick.g2===""} onClick={savePick}><Save size={16}/>{savingPick?"Guardando...":m.prediction_id?"Guardar cambios":"Guardar pronóstico"}</button>{pickMessage&&<small className={pickMessage.startsWith("Pronóstico")?"success-text":"error-text"}>{pickMessage}</small>}</>:<><strong className="big-score">{m.prediction_id?`${m.predicted_team1_goals} – ${m.predicted_team2_goals}`:"Sin pronóstico"}</strong><p>{m.status==="finished"?`${m.total_points||0} puntos obtenidos`:"Las apuestas de este partido están cerradas."}</p></>}</section><section className="content-card"><h2>Distribución</h2>{data.revealed?["team1","draw","team2"].map(key=>{const n=data.distribution.find(x=>x.winner===key)?.count||0;return <div className="distribution" key={key}><span>{key==="team1"?m.team1:key==="team2"?m.team2:"Empate"}</span><i><b style={{width:`${n/total*100}%`}}/></i><strong>{Math.round(n/total*100)}%</strong></div>}):<HiddenDistribution revealAt={m.effective_close_at} onReveal={load}/>}</section></div>
 <section className="content-card participants-card"><button className="participants-toggle" onClick={()=>setParticipantsOpen(!participantsOpen)}><h2>Participantes ({data.participants.filter(p=>p.participating).length})</h2><span>{participantsOpen?"Ocultar":"Mostrar"}<ChevronDown className={participantsOpen?"open":""}/></span></button>{participantsOpen&&<div className="participants">{data.participants.map(p=><div key={p.id}><strong>{p.username}</strong>{!p.participating?<span className="not-participating error-text">Sin participar</span>:data.revealed?<><span>{p.predicted_team1_goals}–{p.predicted_team2_goals}</span><b>+{p.total_points}</b></>:<span>Pronóstico registrado</span>}</div>)}</div>}</section>
 <section id="comentarios" className="content-card comments"><h2><MessageCircle size={20}/> Comentarios</h2><div className="comment-form"><input value={text} onChange={e=>setText(e.target.value)} maxLength="500" placeholder="Comparte tu lectura del partido…"/><button className="primary" disabled={!text.trim()} onClick={add}><Send size={16}/></button></div>{comments.map(c=><article key={c.id}><span className="mini-avatar">{c.username[0].toUpperCase()}</span><div><strong>{c.username}</strong><p>{c.comment}</p><small>{new Date(c.created_at).toLocaleString("es-ES")}</small></div>{(c.user_id===user.id||user.role==="admin")&&<button onClick={()=>remove(c.id)}><Trash2 size={15}/></button>}</article>)}</section></div>
}
